# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poisson_ui.ui'
#
# Created: Wed Sep 03 20:04:26 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1097, 714)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton1DLine = QtGui.QRadioButton(self.centralwidget)
        self.radioButton1DLine.setObjectName(_fromUtf8("radioButton1DLine"))
        self.verticalLayout_2.addWidget(self.radioButton1DLine)
        self.radioButton1DRepeatedLine = QtGui.QRadioButton(self.centralwidget)
        self.radioButton1DRepeatedLine.setObjectName(_fromUtf8("radioButton1DRepeatedLine"))
        self.verticalLayout_2.addWidget(self.radioButton1DRepeatedLine)
        self.radioButton2DDisk = QtGui.QRadioButton(self.centralwidget)
        self.radioButton2DDisk.setChecked(True)
        self.radioButton2DDisk.setObjectName(_fromUtf8("radioButton2DDisk"))
        self.verticalLayout_2.addWidget(self.radioButton2DDisk)
        self.radioButton2DRotatedDisk = QtGui.QRadioButton(self.centralwidget)
        self.radioButton2DRotatedDisk.setObjectName(_fromUtf8("radioButton2DRotatedDisk"))
        self.verticalLayout_2.addWidget(self.radioButton2DRotatedDisk)
        self.radioButton2DRect = QtGui.QRadioButton(self.centralwidget)
        self.radioButton2DRect.setObjectName(_fromUtf8("radioButton2DRect"))
        self.verticalLayout_2.addWidget(self.radioButton2DRect)
        self.radioButton2DRepeatedRectangle = QtGui.QRadioButton(self.centralwidget)
        self.radioButton2DRepeatedRectangle.setObjectName(_fromUtf8("radioButton2DRepeatedRectangle"))
        self.verticalLayout_2.addWidget(self.radioButton2DRepeatedRectangle)
        self.radioButton3DSphere = QtGui.QRadioButton(self.centralwidget)
        self.radioButton3DSphere.setObjectName(_fromUtf8("radioButton3DSphere"))
        self.verticalLayout_2.addWidget(self.radioButton3DSphere)
        self.radioButton3DBox = QtGui.QRadioButton(self.centralwidget)
        self.radioButton3DBox.setObjectName(_fromUtf8("radioButton3DBox"))
        self.verticalLayout_2.addWidget(self.radioButton3DBox)
        self.radioButton3DRepeatedBox = QtGui.QRadioButton(self.centralwidget)
        self.radioButton3DRepeatedBox.setObjectName(_fromUtf8("radioButton3DRepeatedBox"))
        self.verticalLayout_2.addWidget(self.radioButton3DRepeatedBox)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.numberOfPointsSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.numberOfPointsSpinBox.setMinimum(1)
        self.numberOfPointsSpinBox.setMaximum(4096)
        self.numberOfPointsSpinBox.setProperty("value", 8)
        self.numberOfPointsSpinBox.setObjectName(_fromUtf8("numberOfPointsSpinBox"))
        self.gridLayout.addWidget(self.numberOfPointsSpinBox, 1, 1, 1, 1)
        self.firstPointRandomCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.firstPointRandomCheckBox.setChecked(True)
        self.firstPointRandomCheckBox.setObjectName(_fromUtf8("firstPointRandomCheckBox"))
        self.gridLayout.addWidget(self.firstPointRandomCheckBox, 6, 1, 1, 1)
        self.numberOfIterationsPerPointSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.numberOfIterationsPerPointSpinBox.setMinimum(1)
        self.numberOfIterationsPerPointSpinBox.setMaximum(1024)
        self.numberOfIterationsPerPointSpinBox.setProperty("value", 8)
        self.numberOfIterationsPerPointSpinBox.setObjectName(_fromUtf8("numberOfIterationsPerPointSpinBox"))
        self.gridLayout.addWidget(self.numberOfIterationsPerPointSpinBox, 2, 1, 1, 1)
        self.cacheSortBucketsSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.cacheSortBucketsSpinBox.setMaximum(64)
        self.cacheSortBucketsSpinBox.setObjectName(_fromUtf8("cacheSortBucketsSpinBox"))
        self.gridLayout.addWidget(self.cacheSortBucketsSpinBox, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.numberTotalIterationsSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.numberTotalIterationsSpinBox.setMinimum(1)
        self.numberTotalIterationsSpinBox.setMaximum(1048576)
        self.numberTotalIterationsSpinBox.setProperty("value", 64)
        self.numberTotalIterationsSpinBox.setObjectName(_fromUtf8("numberTotalIterationsSpinBox"))
        self.gridLayout.addWidget(self.numberTotalIterationsSpinBox, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.rotationsAsRepetitions = QtGui.QSpinBox(self.centralwidget)
        self.rotationsAsRepetitions.setMaximum(16)
        self.rotationsAsRepetitions.setObjectName(_fromUtf8("rotationsAsRepetitions"))
        self.gridLayout.addWidget(self.rotationsAsRepetitions, 5, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.generateButton = QtGui.QPushButton(self.centralwidget)
        self.generateButton.setObjectName(_fromUtf8("generateButton"))
        self.verticalLayout.addWidget(self.generateButton)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setMaximum(1024)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setFormat(_fromUtf8(""))
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.outputShaderCodeTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.outputShaderCodeTextEdit.setReadOnly(True)
        self.outputShaderCodeTextEdit.setObjectName(_fromUtf8("outputShaderCodeTextEdit"))
        self.verticalLayout.addWidget(self.outputShaderCodeTextEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.horizontalLayout_2.setStretch(2, 2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Poisson-like pattern generator", None))
        self.radioButton1DLine.setText(_translate("MainWindow", "1D line", None))
        self.radioButton1DRepeatedLine.setText(_translate("MainWindow", "1D repeated line", None))
        self.radioButton2DDisk.setText(_translate("MainWindow", "2D disk", None))
        self.radioButton2DRotatedDisk.setText(_translate("MainWindow", "2D rotated disk", None))
        self.radioButton2DRect.setText(_translate("MainWindow", "2D rectangle", None))
        self.radioButton2DRepeatedRectangle.setText(_translate("MainWindow", "2D repeated rectangle", None))
        self.radioButton3DSphere.setText(_translate("MainWindow", "3D sphere", None))
        self.radioButton3DBox.setText(_translate("MainWindow", "3D box", None))
        self.radioButton3DRepeatedBox.setText(_translate("MainWindow", "3D repeated box", None))
        self.firstPointRandomCheckBox.setText(_translate("MainWindow", "First point random", None))
        self.label_2.setText(_translate("MainWindow", "Number of iterations per point", None))
        self.label.setText(_translate("MainWindow", "Number of points", None))
        self.label_4.setText(_translate("MainWindow", "Pattern type", None))
        self.label_5.setText(_translate("MainWindow", "Cache sort buckets", None))
        self.label_3.setText(_translate("MainWindow", "Number of retires", None))
        self.label_6.setToolTip(_translate("MainWindow", "Works only in rotated disk mode - maximizes distances / variances num between rotations - to be used with rotated patterns", None))
        self.label_6.setText(_translate("MainWindow", "Rotations as repetitions (num)", None))
        self.rotationsAsRepetitions.setToolTip(_translate("MainWindow", "Works only in rotated disk mode - maximizes distances / variances num between rotations - to be used with rotated patterns", None))
        self.generateButton.setText(_translate("MainWindow", "Generate", None))

